# Generated by Django 5.2.11 on 2026-02-12 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('animal_type', models.CharField(choices=[('cattle', 'Cattle'), ('goat', 'Goat'), ('sheep', 'Sheep'), ('poultry', 'Poultry')], max_length=20)),
                ('breed', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=6)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('pregnant', 'Pregnant'), ('quarantine', 'Quarantine')], default='healthy', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Livestock',
                'db_table': 'livestock',
                'ordering': ['-created_at'],
            },
        ),
    ]
