# Generated by Django 5.2.11 on 2026-04-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('animal_health', 'Animal Health'), ('farm_management', 'Farm Management'), ('market_info', 'Market Info'), ('nutrition', 'Nutrition'), ('government_programs', 'Government Programs')], max_length=30)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='training/')),
                ('external_link', models.URLField(blank=True)),
                ('read_time', models.IntegerField(help_text='Estimated read time in minutes')),
                ('is_featured', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'training_resources',
                'ordering': ['-published_date'],
            },
        ),
    ]
